# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Districting Plan Evaluation
tagline:          ''
description:      'A 2021 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2021-redistricting-website"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2021-redistricting-website/
